plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

sourceSets {
    main {
        java {
            include 'me/cortex/voxy/forge/**'
            include 'me/cortex/voxy/platform/**'
            include 'me/cortex/voxy/config/**'
            include 'me/cortex/voxy/common/util/Pair.java'
            include 'me/cortex/voxy/common/util/GlobalCleaner.java'
            include 'me/cortex/voxy/common/util/ByteBufferBackedInputStream.java'
            include 'me/cortex/voxy/common/util/AllocationArena.java'
            include 'me/cortex/voxy/common/util/HierarchicalBitSet.java'
            include 'me/cortex/voxy/common/util/TrackedObject.java'
            include 'me/cortex/voxy/common/util/UnsafeUtil.java'
            include 'me/cortex/voxy/common/util/MemoryBuffer.java'
            include 'me/cortex/voxy/common/util/ThreadLocalMemoryBuffer.java'
            include 'me/cortex/voxy/common/voxelization/VoxelizedSection.java'
            include 'me/cortex/voxy/common/voxelization/ILightingSupplier.java'
            include 'me/cortex/voxy/common/voxelization/WorldConversionFactory.java'
            include 'me/cortex/voxy/common/voxelization/WorldVoxilizedSectionMipper.java'
            include 'me/cortex/voxy/common/world/WorldSection.java'
            include 'me/cortex/voxy/common/world/ActiveSectionTracker.java'
            include 'me/cortex/voxy/common/world/WorldEngine.java'
            include 'me/cortex/voxy/common/world/WorldUpdater.java'
            include 'me/cortex/voxy/common/world/SaveLoadSystem3.java'
            include 'me/cortex/voxy/common/world/other/Mapper.java'
            include 'me/cortex/voxy/common/world/other/Mipper.java'
            include 'me/cortex/voxy/common/world/service/VoxelIngestService.java'
            include 'me/cortex/voxy/common/config/IMappingStorage.java'
            include 'me/cortex/voxy/common/config/IStoredSectionPositionIterator.java'
            include 'me/cortex/voxy/common/config/section/SectionStorage.java'
            include 'me/cortex/voxy/common/config/section/SectionSerializationStorage.java'
            include 'me/cortex/voxy/common/config/storage/StorageBackend.java'
            include 'me/cortex/voxy/common/config/storage/inmemory/MemoryStorageBackend.java'
            include 'me/cortex/voxy/common/config/compressors/StorageCompressor.java'
        }
        resources {
            include 'META-INF/mods.toml'
            include 'pack.mcmeta'
        }
    }
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'

            mods {
                voxy {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', project.mod_id
            def quickPlayWorld = (project.findProperty('voxyQuickPlayWorld') ?: '新的世界').toString()
            args '--quickPlaySingleplayer', quickPlayWorld
        }

        server {
            property 'forge.enabledGameTestNamespaces', project.mod_id
            args '--nogui'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    implementation "it.unimi.dsi:fastutil:${project.fastutil_version}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : project.minecraft_version,
            minecraft_version_range: project.minecraft_version_range,
            forge_version          : project.forge_version,
            forge_version_range    : project.forge_version_range,
            loader_version_range   : project.loader_version_range,
            embeddium_version_range: project.embeddium_version_range,
            oculus_version_range   : project.oculus_version_range,
            mod_id                 : project.mod_id,
            mod_name               : project.mod_name,
            mod_license            : project.mod_license,
            mod_version            : project.mod_version,
            mod_authors            : project.mod_authors,
            mod_description        : project.mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : project.mod_id,
                'Specification-Vendor'    : project.mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.mod_name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : project.mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')
