package me.cortex.voxy.forge;

record ForgeFormalTexturedShaderPreviewAuditResult(
        boolean success,
        String error,
        double durationMs,
        boolean i6SafeSetExists,
        boolean j2ValidationReady,
        boolean shaderCompileOk,
        boolean programLinkOk,
        boolean modelDataBindingOk,
        boolean modelColourBindingOk,
        boolean atlasTextureBindingOk,
        boolean samplerBindingOk,
        boolean bindingLayoutCompatible,
        boolean blockModelRecordLayoutCompatible,
        boolean formalModelIdsAddressable,
        boolean placeholderIdUsed,
        boolean sampleSetIdUsed,
        boolean sampleSetBridgeUsedAsFormalSource,
        boolean offscreenPreviewReady,
        boolean previewFramebufferComplete,
        boolean previewReadbackOk,
        int previewPixelMismatches,
        int previewChecksumCount,
        boolean previewDrawOnly,
        boolean visiblePreviewEnabled,
        boolean terrainDrawStarted,
        boolean formalRendererDrawStarted,
        boolean actualRendererDrawEnabled,
        boolean formalTexturedShaderReady,
        boolean formalRendererReady
) {
    static ForgeFormalTexturedShaderPreviewAuditResult failure(String error, double durationMs) {
        return new ForgeFormalTexturedShaderPreviewAuditResult(
                false,
                error == null || error.isBlank() ? "unknown" : error,
                durationMs,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                true,
                false,
                false,
                false,
                false,
                false,
                false
        );
    }
}
