package me.cortex.voxy.forge;

record ForgeModelStoreStats(
        String stage,
        String layoutVersion,
        boolean formalLayoutCompatible,
        String placeholderLayoutVersion,
        String formalModelLayoutVersion,
        int formalModelRecordBytes,
        boolean formalLayoutKnown,
        boolean fieldMappingReady,
        boolean faceDataMappingReady,
        boolean atlasUvMappingReady,
        boolean materialMappingReady,
        long buildRuns,
        long clearRuns,
        String lastBuildError,
        double lastBuildDurationMs,
        boolean placeholderModelStoreReady,
        int placeholderModelRecords,
        int placeholderModelRecordBytes,
        boolean placeholderModelDataBufferCreated,
        boolean placeholderModelDataBufferReady,
        long placeholderModelDataBufferBytes,
        boolean placeholderModelColourBufferCreated,
        boolean placeholderModelColourBufferReady,
        long placeholderModelColourBufferBytes,
        boolean realModelStoreReady,
        boolean realModelFactoryReady,
        boolean modelBakeryBridgeReady,
        boolean textureAtlasReady,
        boolean realModelDataBufferReady,
        boolean realModelColourBufferReady,
        boolean biomeTintReady,
        boolean lightmapReady,
        boolean resourceReloadReady,
        boolean formalShaderInputsReady,
        boolean formalModelBridgeReady,
        long generation,
        String dimension,
        boolean bufferStale,
        long auditRuns,
        long auditFailures,
        boolean lastAuditOk,
        String lastAuditError,
        double lastAuditDurationMs,
        int lastAuditedRecords,
        long lastAuditedBytes,
        int lastInvalidRecords,
        boolean lastModelDataBufferMatch,
        boolean lastModelColourBufferMatch,
        int sampleModelId,
        int sampleBlockStateId,
        String sampleBlockState,
        boolean samplePlaceholder,
        boolean sampleHasFaceData,
        boolean sampleHasAtlasUv,
        boolean sampleHasTexture,
        boolean sampleHasRealModelMetadata
) {
    static ForgeModelStoreStats empty(long clearRuns) {
        return new ForgeModelStoreStats(
                ForgeModelStoreSkeleton.STAGE,
                ForgeModelStoreLayout.LAYOUT_VERSION,
                ForgeModelStoreLayout.FORMAL_LAYOUT_COMPATIBLE,
                ForgeModelStoreLayout.LAYOUT_VERSION,
                ForgeModelStoreFormalLayout.LAYOUT_VERSION,
                ForgeModelStoreFormalLayout.MODEL_RECORD_BYTES,
                ForgeModelStoreFormalLayout.FORMAL_LAYOUT_KNOWN,
                ForgeModelStoreFormalLayout.FIELD_MAPPING_READY,
                ForgeModelStoreFormalLayout.FACE_DATA_MAPPING_READY,
                ForgeModelStoreFormalLayout.ATLAS_UV_MAPPING_READY,
                ForgeModelStoreFormalLayout.MATERIAL_MAPPING_READY,
                0L,
                clearRuns,
                "none",
                0.0D,
                false,
                0,
                ForgeModelStoreLayout.BYTES,
                false,
                false,
                0L,
                false,
                false,
                0L,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                -1L,
                "none",
                false,
                0L,
                0L,
                false,
                "none",
                0.0D,
                0,
                0L,
                0,
                false,
                false,
                -1,
                -1,
                "none",
                true,
                false,
                false,
                false,
                false
        );
    }
}
