package me.cortex.voxy.forge;

import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;

/**
 * Legacy K-preview command registration split out of ForgeVoxyCommands.
 *
 * <p>These commands are historical validation and visible-preview routes. They
 * are not the original-Voxy parity renderer route.</p>
 */
@Deprecated(forRemoval = false)
final class ForgeVoxyLegacyKPreviewCommands {
    private ForgeVoxyLegacyKPreviewCommands() {
    }

    static void register(LiteralArgumentBuilder<CommandSourceStack> root) {
        root.then(Commands.literal("formal_cmdgen_gpu_validate_build")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenGpuValidateBuild(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_gpu_validate_status")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenGpuValidateStatus(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_gpu_validate_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenGpuValidateAudit(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_gpu_validate_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenGpuValidateDump(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_gpu_validate_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenGpuValidateClear(ctx.getSource())))
                .then(Commands.literal("qa_k5_formal_cmdgen_gpu_validation")
                        .executes(ctx -> ForgeVoxyCommands.qaK5FormalCmdgenGpuValidation(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_real_section_dry_run_build")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenRealSectionDryRunBuild(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_real_section_dry_run_status")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenRealSectionDryRunStatus(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_real_section_dry_run_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenRealSectionDryRunAudit(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_real_section_dry_run_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenRealSectionDryRunDump(ctx.getSource())))
                .then(Commands.literal("formal_cmdgen_real_section_dry_run_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalCmdgenRealSectionDryRunClear(ctx.getSource())))
                .then(Commands.literal("qa_k6_formal_cmdgen_real_section_dry_run")
                        .executes(ctx -> ForgeVoxyCommands.qaK6FormalCmdgenRealSectionDryRun(ctx.getSource())))
                .then(Commands.literal("formal_isolated_mdic_draw_build")
                        .executes(ctx -> ForgeVoxyCommands.formalIsolatedMdicDrawBuild(ctx.getSource())))
                .then(Commands.literal("formal_isolated_mdic_draw_status")
                        .executes(ctx -> ForgeVoxyCommands.formalIsolatedMdicDrawStatus(ctx.getSource())))
                .then(Commands.literal("formal_isolated_mdic_draw_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalIsolatedMdicDrawAudit(ctx.getSource())))
                .then(Commands.literal("formal_isolated_mdic_draw_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalIsolatedMdicDrawDump(ctx.getSource())))
                .then(Commands.literal("formal_isolated_mdic_draw_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalIsolatedMdicDrawClear(ctx.getSource())))
                .then(Commands.literal("qa_k7_formal_isolated_mdic_draw")
                        .executes(ctx -> ForgeVoxyCommands.qaK7FormalIsolatedMdicDraw(ctx.getSource())))
                .then(Commands.literal("formal_model_id_geometry_path_build")
                        .executes(ctx -> ForgeVoxyCommands.formalModelIdGeometryPathBuild(ctx.getSource())))
                .then(Commands.literal("formal_model_id_geometry_path_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelIdGeometryPathStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_id_geometry_path_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelIdGeometryPathAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_id_geometry_path_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalModelIdGeometryPathDump(ctx.getSource())))
                .then(Commands.literal("formal_model_id_geometry_path_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelIdGeometryPathClear(ctx.getSource())))
                .then(Commands.literal("qa_k8_formal_model_id_geometry_path")
                        .executes(ctx -> ForgeVoxyCommands.qaK8FormalModelIdGeometryPath(ctx.getSource())))
                .then(Commands.literal("formal_terrain_shader_integration_build")
                        .executes(ctx -> ForgeVoxyCommands.formalTerrainShaderIntegrationBuild(ctx.getSource())))
                .then(Commands.literal("formal_terrain_shader_integration_status")
                        .executes(ctx -> ForgeVoxyCommands.formalTerrainShaderIntegrationStatus(ctx.getSource())))
                .then(Commands.literal("formal_terrain_shader_integration_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalTerrainShaderIntegrationAudit(ctx.getSource())))
                .then(Commands.literal("formal_terrain_shader_integration_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalTerrainShaderIntegrationDump(ctx.getSource())))
                .then(Commands.literal("formal_terrain_shader_integration_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalTerrainShaderIntegrationClear(ctx.getSource())))
                .then(Commands.literal("qa_k9_formal_terrain_shader_integration")
                        .executes(ctx -> ForgeVoxyCommands.qaK9FormalTerrainShaderIntegration(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewEnable(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewDisable(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_prepare")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewPrepare(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_prepare_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewPrepareStatus(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_observe_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveEnable(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_observe_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDisable(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_observe_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveStatus(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_observe_draw_pause")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDrawPause(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_observe_draw_resume")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDrawResume(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewStatus(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewAudit(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewDump(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewClear(ctx.getSource())))
                .then(Commands.literal("qa_k10_formal_visible_lod_preview")
                        .executes(ctx -> ForgeVoxyCommands.qaK10FormalVisibleLodPreview(ctx.getSource())))
                .then(Commands.literal("qa_k10_visible_preview_observe_performance")
                        .executes(ctx -> ForgeVoxyCommands.qaK10VisiblePreviewObservePerformance(ctx.getSource())))
                .then(Commands.literal("qa_k10_visible_preview_observe_timeout")
                        .executes(ctx -> ForgeVoxyCommands.qaK10VisiblePreviewObserveTimeout(ctx.getSource())))
                .then(Commands.literal("qa_k10_visible_preview_observe_prepare")
                        .executes(ctx -> ForgeVoxyCommands.qaK10VisiblePreviewObservePrepare(ctx.getSource())))
                .then(Commands.literal("qa_k11_formal_visible_lod_preview_prewarm")
                        .executes(ctx -> ForgeVoxyCommands.qaK11FormalVisibleLodPreviewPrewarm(ctx.getSource())))
                .then(Commands.literal("qa_k12_k13_visible_preview_prepare_reuse")
                        .executes(ctx -> ForgeVoxyCommands.qaK12K13VisiblePreviewPrepareReuse(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_multi_section_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewMultiSectionStatus(ctx.getSource())))
                .then(Commands.literal("qa_k14_k16_multi_section_visible_preview")
                        .executes(ctx -> ForgeVoxyCommands.qaK14K16MultiSectionVisiblePreview(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_world_placed_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewWorldPlacedStatus(ctx.getSource())))
                .then(Commands.literal("qa_k17_k18_world_placed_visible_preview")
                        .executes(ctx -> ForgeVoxyCommands.qaK17K18WorldPlacedVisiblePreview(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_section_metadata_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewSectionMetadataStatus(ctx.getSource())))
                .then(Commands.literal("qa_k19_k20_section_metadata_visible_preview")
                        .executes(ctx -> ForgeVoxyCommands.qaK19K20SectionMetadataVisiblePreview(ctx.getSource())))
                .then(Commands.literal("formal_visible_lod_preview_command_bucket_status")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewCommandBucketStatus(ctx.getSource())))
                .then(Commands.literal("qa_k21_k22_command_bucket_visible_preview")
                        .executes(ctx -> ForgeVoxyCommands.qaK21K22CommandBucketVisiblePreview(ctx.getSource())))
                .then(Commands.literal("formal_minimal_lod_renderer_prepare")
                        .executes(ctx -> ForgeVoxyCommands.formalMinimalLodRendererPrepare(ctx.getSource())))
                .then(Commands.literal("formal_minimal_lod_renderer_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveEnable(ctx.getSource())))
                .then(Commands.literal("formal_minimal_lod_renderer_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDisable(ctx.getSource())))
                .then(Commands.literal("formal_minimal_lod_renderer_status")
                        .executes(ctx -> ForgeVoxyCommands.formalMinimalLodRendererStatus(ctx.getSource())))
                .then(Commands.literal("qa_k23_k30_minimal_formal_lod_renderer")
                        .executes(ctx -> ForgeVoxyCommands.qaK23K30MinimalFormalLodRenderer(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_moving_prepare")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewMovingPrepare(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_moving_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewMovingEnable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_moving_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDisable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_moving_status")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewMovingStatus(ctx.getSource())))
                .then(Commands.literal("qa_k31_k36_formal_lod_preview_moving_patch")
                        .executes(ctx -> ForgeVoxyCommands.qaK31K36FormalLodPreviewMovingPatch(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_expanded_prepare")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewExpandedPrepare(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_expanded_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewExpandedEnable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_expanded_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDisable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_expanded_status")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewExpandedStatus(ctx.getSource())))
                .then(Commands.literal("qa_k37_k42_expanded_formal_lod_patch")
                        .executes(ctx -> ForgeVoxyCommands.qaK37K42ExpandedFormalLodPatch(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_update_prepare")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewUpdatePrepare(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_update_status")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewUpdateStatus(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_update_rebuild_if_needed")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewUpdateRebuildIfNeeded(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_update_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewUpdateEnable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_update_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalVisibleLodPreviewObserveDisable(ctx.getSource())))
                .then(Commands.literal("qa_k43_k48_formal_lod_preview_update_lifecycle")
                        .executes(ctx -> ForgeVoxyCommands.qaK43K48FormalLodPreviewUpdateLifecycle(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_auto_update_enable")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewAutoUpdateEnable(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_auto_update_status")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewAutoUpdateStatus(ctx.getSource())))
                .then(Commands.literal("formal_lod_preview_auto_update_disable")
                        .executes(ctx -> ForgeVoxyCommands.formalLodPreviewAutoUpdateDisable(ctx.getSource())))
                .then(Commands.literal("qa_k49_k54_formal_lod_preview_auto_update")
                        .executes(ctx -> ForgeVoxyCommands.qaK49K54FormalLodPreviewAutoUpdate(ctx.getSource())));
    }
}
