package me.cortex.voxy.forge;

import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;

/**
 * Model pipeline command registration for the original-Voxy parity route.
 *
 * <p>Some historical sample-set commands are still registered here only until
 * their owners can be deleted without breaking compilation.</p>
 */
final class ForgeVoxyModelPipelineCommands {
    private ForgeVoxyModelPipelineCommands() {
    }

    static void register(LiteralArgumentBuilder<CommandSourceStack> root) {
        root.then(Commands.literal("model_bridge_check")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeCheck(ctx.getSource())))
                .then(Commands.literal("model_bridge_status")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeStatus(ctx.getSource())))
                .then(Commands.literal("model_bridge_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeClear(ctx.getSource())))
                .then(Commands.literal("model_bridge_dump_sample")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeDumpSample(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_build")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonBuild(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_status")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonStatus(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonAudit(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_dump_sample")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonDumpSample(ctx.getSource())))
                .then(Commands.literal("model_store_skeleton_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreSkeletonClear(ctx.getSource())))
                .then(Commands.literal("model_store_layout_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreLayoutAudit(ctx.getSource())))
                .then(Commands.literal("model_store_layout_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreLayoutAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_store_layout_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreLayoutAuditClear(ctx.getSource())))
                .then(Commands.literal("model_bridge_resource_reload_status")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeResourceReloadStatus(ctx.getSource())))
                .then(Commands.literal("model_bridge_resource_reload_clear_stats")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeResourceReloadClearStats(ctx.getSource())))
                .then(Commands.literal("model_bridge_simulate_resource_reload")
                        .executes(ctx -> ForgeVoxyCommands.modelBridgeSimulateResourceReload(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_check")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeCheck(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_status")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeStatus(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_audit")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeAudit(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeAuditStatus(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_dump_sample")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeDumpSample(ctx.getSource())))
                .then(Commands.literal("baked_model_bridge_clear")
                        .executes(ctx -> ForgeVoxyCommands.bakedModelBridgeClear(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_build")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleBuild(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_status")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleStatus(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleAudit(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_dump")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleDump(ctx.getSource())))
                .then(Commands.literal("model_store_real_sample_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelStoreRealSampleClear(ctx.getSource())))
                .then(Commands.literal("model_sample_set_build")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetBuild(ctx.getSource())))
                .then(Commands.literal("model_sample_set_status")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetStatus(ctx.getSource())))
                .then(Commands.literal("model_sample_set_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetAudit(ctx.getSource())))
                .then(Commands.literal("model_sample_set_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_sample_set_dump")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetDump(ctx.getSource())))
                .then(Commands.literal("model_sample_set_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelSampleSetClear(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_build")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonBuild(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_status")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonStatus(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonAudit(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_dump_sample")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonDumpSample(ctx.getSource())))
                .then(Commands.literal("model_atlas_skeleton_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasSkeletonClear(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_sample")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadSample(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_status")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadStatus(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadAudit(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadAuditStatus(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_dump_sample")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadDumpSample(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_clear")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadClear(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_sample_set")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadSampleSet(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_sample_set_status")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadSampleSetStatus(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_sample_set_audit")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadSampleSetAudit(ctx.getSource())))
                .then(Commands.literal("model_atlas_upload_sample_set_dump")
                        .executes(ctx -> ForgeVoxyCommands.modelAtlasUploadSampleSetDump(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_bridge_build")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBridgeBuild(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_bridge_status")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBridgeStatus(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_bridge_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBridgeAudit(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_bridge_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBridgeAuditStatus(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_bridge_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBridgeClear(ctx.getSource())))
                .then(Commands.literal("formal_model_store_build")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreBuild(ctx.getSource())))
                .then(Commands.literal("formal_model_store_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_store_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_store_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreAuditStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_store_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreClear(ctx.getSource())))
                .then(Commands.literal("formal_model_store_dump_layout")
                        .executes(ctx -> ForgeVoxyCommands.formalModelStoreDumpLayout(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_request_current")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryRequestCurrent(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_request_blockstate")
                        .then(Commands.argument("blockStateId", IntegerArgumentType.integer())
                                .executes(ctx -> ForgeVoxyCommands.formalModelFactoryRequestBlockState(ctx.getSource(), IntegerArgumentType.getInteger(ctx, "blockStateId")))))
                .then(Commands.literal("formal_model_factory_process_skeleton")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryProcessSkeleton(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryAuditStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryClear(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_dump_mappings")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryDumpMappings(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_one_current")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeOneCurrent(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_one_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeOneStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_one_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeOneAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_one_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeOneDump(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_one_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeOneClear(ctx.getSource())))
                .then(Commands.literal("qa_i4_formal_bake_upload")
                        .executes(ctx -> ForgeVoxyCommands.qaI4FormalBakeUpload(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_multi_safe")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeMultiSafe(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_multi_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeMultiStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_multi_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeMultiAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_multi_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeMultiDump(ctx.getSource())))
                .then(Commands.literal("formal_model_factory_bake_multi_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelFactoryBakeMultiClear(ctx.getSource())))
                .then(Commands.literal("qa_i5_multi_block_bake_upload")
                        .executes(ctx -> ForgeVoxyCommands.qaI5MultiBlockBakeUpload(ctx.getSource())))
                .then(Commands.literal("formal_model_bakery_lifecycle_status")
                        .executes(ctx -> ForgeVoxyCommands.formalModelBakeryLifecycleStatus(ctx.getSource())))
                .then(Commands.literal("formal_model_bakery_lifecycle_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalModelBakeryLifecycleAudit(ctx.getSource())))
                .then(Commands.literal("formal_model_bakery_lifecycle_rebuild_safe_set")
                        .executes(ctx -> ForgeVoxyCommands.formalModelBakeryLifecycleRebuildSafeSet(ctx.getSource())))
                .then(Commands.literal("formal_model_bakery_lifecycle_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalModelBakeryLifecycleDump(ctx.getSource())))
                .then(Commands.literal("formal_model_bakery_lifecycle_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalModelBakeryLifecycleClear(ctx.getSource())))
                .then(Commands.literal("qa_i6_model_lifecycle_rebuild")
                        .executes(ctx -> ForgeVoxyCommands.qaI6ModelLifecycleRebuild(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_build")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputBuild(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_status")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputStatus(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputAudit(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputDump(ctx.getSource())))
                .then(Commands.literal("formal_shader_input_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderInputClear(ctx.getSource())))
                .then(Commands.literal("qa_j1_formal_shader_input")
                        .executes(ctx -> ForgeVoxyCommands.qaJ1FormalShaderInput(ctx.getSource())))
                .then(Commands.literal("formal_shader_program_build")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderProgramBuild(ctx.getSource())))
                .then(Commands.literal("formal_shader_program_status")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderProgramStatus(ctx.getSource())))
                .then(Commands.literal("formal_shader_program_audit")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderProgramAudit(ctx.getSource())))
                .then(Commands.literal("formal_shader_program_dump")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderProgramDump(ctx.getSource())))
                .then(Commands.literal("formal_shader_program_clear")
                        .executes(ctx -> ForgeVoxyCommands.formalShaderProgramClear(ctx.getSource())))
                .then(Commands.literal("qa_j2_formal_shader_program")
                        .executes(ctx -> ForgeVoxyCommands.qaJ2FormalShaderProgram(ctx.getSource())));
    }
}
