package me.cortex.voxy.forge;

record ForgeFormalPackedQuadPreviewAuditResult(
        boolean success,
        String error,
        double durationMs,
        boolean i6SafeSetExists,
        boolean j3PreviewWorks,
        boolean packedQuadRecordsMapped,
        boolean placeholderIdUsed,
        boolean sampleSetIdUsed,
        boolean sampleSetBridgeUsedAsFormalSource,
        boolean originalGeometryUntouched,
        boolean temporaryFormalQuadBufferIsolated,
        boolean temporaryFormalQuadBufferCreated,
        boolean quadRecordDecodeOk,
        boolean modelIdDecodeOk,
        boolean faceDecodeOk,
        boolean offscreenPreviewReady,
        boolean previewFramebufferComplete,
        boolean previewReadbackOk,
        int previewPixelMismatches,
        int previewChecksumCount,
        boolean previewDrawOnly,
        boolean terrainDrawStarted,
        boolean formalRendererDrawStarted,
        boolean actualRendererDrawEnabled,
        boolean formalTexturedShaderReady,
        boolean formalRendererReady
) {
    static ForgeFormalPackedQuadPreviewAuditResult failure(String error, double durationMs) {
        return new ForgeFormalPackedQuadPreviewAuditResult(
                false,
                error == null || error.isBlank() ? "unknown" : error,
                durationMs,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                true,
                false,
                false,
                false,
                false,
                false
        );
    }
}
