package me.cortex.voxy.forge;

record ForgeFormalIsolatedMdicDrawSmokeTestAuditResult(
        boolean success,
        String error,
        double durationMs,
        boolean k1OwnerExists,
        boolean k2ViewportOwnerExists,
        boolean k3CommandGenerationOwnerExists,
        boolean k4VisibilityOwnerExists,
        boolean k5ValidationProgramExists,
        boolean k6RealSectionDryRunExists,
        boolean originalMdicSectionRendererInspected,
        boolean originalShaderBindingsInspected,
        boolean drawInputUsesK6Command,
        boolean realSectionCommandUsed,
        boolean syntheticDrawFixtureUsed,
        boolean validationBuffersIsolated,
        boolean debugMdicCommandBuffersUsedAsFormal,
        boolean originalGeometryHeapMutated,
        boolean offscreenFramebufferComplete,
        boolean offscreenValidationDrawExecuted,
        boolean offscreenReadbackOk,
        int offscreenNonZeroPixelCount,
        boolean drawCommandAccepted,
        boolean drawCountAccepted,
        boolean drawCommandMatchesK6,
        boolean geometryInputAvailable,
        boolean modelInputAvailable,
        boolean shaderInputAvailable,
        boolean glMultiDrawElementsIndirectCountCalled,
        boolean visibleTerrainDrawExecuted,
        boolean liveRendererDrawExecuted,
        boolean minecraftMainFramebufferDrawn,
        boolean mdicSectionRendererCalled,
        boolean voxyRenderSystemCalled,
        boolean formalDrawPipelineReady,
        boolean formalRendererReady,
        boolean actualRendererDrawEnabled
) {
    static ForgeFormalIsolatedMdicDrawSmokeTestAuditResult failure(String error, double durationMs) {
        return new ForgeFormalIsolatedMdicDrawSmokeTestAuditResult(
                false,
                error == null || error.isBlank() ? "unspecified" : error.replace(' ', '-'),
                durationMs,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
        );
    }
}
