package me.cortex.voxy.forge;

import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;

/**
 * Legacy debug/prototype command registration split out of ForgeVoxyCommands.
 *
 * <p>These commands are retained only while their deprecated renderer owners are
 * still compiled. They must not become part of the original-Voxy parity route.</p>
 */
@Deprecated(forRemoval = false)
final class ForgeVoxyLegacyDebugCommands {
    private ForgeVoxyLegacyDebugCommands() {
    }

    static void register(LiteralArgumentBuilder<CommandSourceStack> root) {
        root.then(Commands.literal("geometry_gpu_upload_status")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuUploadStatus(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_validate_sample")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuValidateSample(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_audit_sample")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuAuditSample(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuAuditStatus(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuAuditClear(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_stress_status")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuStressStatus(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_stress_clear")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuStressClear(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_stress_once")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuStressOnce(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_visualize_sample")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuVisualizeSample(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_visualize_status")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuVisualizeStatus(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_visualize_clear")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuVisualizeClear(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_visualize_enable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuVisualization(ctx.getSource(), true)))
                .then(Commands.literal("geometry_gpu_visualize_disable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuVisualization(ctx.getSource(), false)))
                .then(Commands.literal("geometry_gpu_readback_mesh_build")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuReadbackMeshBuild(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_readback_mesh_status")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuReadbackMeshStatus(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_readback_mesh_clear")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuReadbackMeshClear(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_readback_mesh_refresh_enable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuReadbackMeshAutoRefresh(ctx.getSource(), true)))
                .then(Commands.literal("geometry_gpu_readback_mesh_refresh_disable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuReadbackMeshAutoRefresh(ctx.getSource(), false)))
                .then(Commands.literal("geometry_gpu_readback_mesh_refresh_once")
                        .executes(ctx -> ForgeVoxyCommands.geometryGpuReadbackMeshRefreshOnce(ctx.getSource())))
                .then(Commands.literal("geometry_gpu_upload_enable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuUpload(ctx.getSource(), true)))
                .then(Commands.literal("geometry_gpu_upload_disable")
                        .executes(ctx -> ForgeVoxyCommands.setGeometryGpuUpload(ctx.getSource(), false)))
                .then(Commands.literal("geometry_gpu_upload_clear")
                        .executes(ctx -> ForgeVoxyCommands.clearGeometryGpuUpload(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_enable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRenderer(ctx.getSource(), true)))
                .then(Commands.literal("direct_gl_renderer_disable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRenderer(ctx.getSource(), false)))
                .then(Commands.literal("direct_gl_renderer_clear")
                        .executes(ctx -> ForgeVoxyCommands.clearDirectGlRenderer(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_plan_sample")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererPlanSample(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_build_draw_list")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererBuildDrawList(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_draw_enable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDraw(ctx.getSource(), true)))
                .then(Commands.literal("direct_gl_renderer_draw_disable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDraw(ctx.getSource(), false)))
                .then(Commands.literal("direct_gl_renderer_draw_mode")
                        .then(Commands.literal("loop")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDrawMode(ctx.getSource(), ForgeDirectGpuGeometryDrawMode.LOOP_PER_SECTION)))
                        .then(Commands.literal("multi_draw_arrays")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDrawMode(ctx.getSource(), ForgeDirectGpuGeometryDrawMode.MULTI_DRAW_ARRAYS)))
                        .then(Commands.literal("indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDrawMode(ctx.getSource(), ForgeDirectGpuGeometryDrawMode.MULTI_DRAW_ARRAYS_INDIRECT)))
                        .then(Commands.literal("multi_draw_arrays_indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDrawMode(ctx.getSource(), ForgeDirectGpuGeometryDrawMode.MULTI_DRAW_ARRAYS_INDIRECT)))
                        .then(Commands.literal("auto")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererDrawMode(ctx.getSource(), ForgeDirectGpuGeometryDrawMode.AUTO))))
                .then(Commands.literal("direct_gl_renderer_shader_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererShaderStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_draw_list_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_auto_plan_enable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererAutoPlan(ctx.getSource(), true)))
                .then(Commands.literal("direct_gl_renderer_auto_plan_disable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlRendererAutoPlan(ctx.getSource(), false)))
                .then(Commands.literal("direct_gl_renderer_auto_plan_once")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererAutoPlanOnce(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_auto_plan_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_indirect_audit")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererIndirectAudit(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_indirect_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererIndirectAuditStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_indirect_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererIndirectAuditClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_stress_once")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStressOnce(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_stress_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStressStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_renderer_stress_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlRendererStressClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_plan_sample")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicPlanSample(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_build_buffer")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicBuildBuffer(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_audit")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicAudit(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicAuditStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicAuditClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_stress_once")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicStressOnce(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_stress_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicStressStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_stress_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicStressClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_enable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDraw(ctx.getSource(), true)))
                .then(Commands.literal("direct_gl_mdic_draw_disable")
                        .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDraw(ctx.getSource(), false)))
                .then(Commands.literal("direct_gl_mdic_draw_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_shader_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicShaderStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_mode")
                        .then(Commands.literal("loop")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.LOOP_PER_COMMAND)))
                        .then(Commands.literal("multi_draw_arrays")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ARRAYS)))
                        .then(Commands.literal("indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ARRAYS_INDIRECT)))
                        .then(Commands.literal("multi_draw_arrays_indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ARRAYS_INDIRECT)))
                        .then(Commands.literal("elements_indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ELEMENTS_INDIRECT)))
                        .then(Commands.literal("multi_draw_elements_indirect")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ELEMENTS_INDIRECT)))
                        .then(Commands.literal("elements_indirect_count")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ELEMENTS_INDIRECT_COUNT)))
                        .then(Commands.literal("multi_draw_elements_indirect_count")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ELEMENTS_INDIRECT_COUNT)))
                        .then(Commands.literal("count")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.MULTI_DRAW_ELEMENTS_INDIRECT_COUNT)))
                        .then(Commands.literal("auto")
                                .executes(ctx -> ForgeVoxyCommands.setDirectGlMdicDrawMode(ctx.getSource(), ForgeMdicDebugDrawMode.AUTO))))
                .then(Commands.literal("direct_gl_mdic_draw_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_indirect_audit")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawIndirectAudit(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_indirect_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawIndirectAuditStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_indirect_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawIndirectAuditClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_elements_indirect_audit")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawElementsIndirectAudit(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_elements_indirect_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawElementsIndirectAuditStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_elements_indirect_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawElementsIndirectAuditClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_count_audit")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawCountAudit(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_count_audit_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawCountAuditStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_count_audit_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawCountAuditClear(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_stress_once")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawStressOnce(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_stress_status")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawStressStatus(ctx.getSource())))
                .then(Commands.literal("direct_gl_mdic_draw_stress_clear")
                        .executes(ctx -> ForgeVoxyCommands.directGlMdicDrawStressClear(ctx.getSource())));
    }
}
