package me.cortex.voxy.forge;

public record ForgeSectionGeometryStats(
        String activeDimension,
        int activeSections,
        int maxSections,
        long usedGeometryItems,
        long usedGeometryBytes,
        long arenaSizeItems,
        long arenaLimitItems,
        long arenaFreeItems,
        int arenaFreeBlocks,
        int arenaLargestFreeBlockItems,
        int uploadIntents,
        long uploadIntentItems,
        long uploadIntentBytes,
        int removeIntents,
        long removeIntentItems,
        long removeIntentBytes,
        int dirtyMetadataIds,
        int metadataSlots,
        int metadataValid,
        int metadataInvalid,
        String lastMetadataError,
        int sectionIdHighWaterMark,
        long totalUploads,
        long totalRemoves,
        long totalReplacements,
        long clearCount,
        int sampleSectionId,
        String sampleMetadataWords,
        String sampleMetadataDecoded,
        String sampleOffsets,
        String sampleDeltas,
        int sampleUploadIntentHash,
        String sampleFirstRecordsDecoded
) {
}
