package me.cortex.voxy.forge;

record ForgeModelAtlasStats(
        String stage,
        long buildRuns,
        long clearRuns,
        long auditRuns,
        long auditFailures,
        String lastBuildError,
        double lastBuildDurationMs,
        boolean atlasSkeletonReady,
        boolean atlasLayoutReady,
        boolean atlasOwnershipReady,
        boolean atlasTextureObjectCreated,
        boolean atlasSamplerReady,
        int atlasTextureObjectId,
        int atlasSamplerId,
        int modelTextureSize,
        int modelGridWidth,
        int modelGridHeight,
        int atlasWidth,
        int atlasHeight,
        int facesPerModelX,
        int facesPerModelY,
        boolean faceTileOrderKnown,
        boolean atlasPixelsUploaded,
        boolean realTextureDataReady,
        boolean customAtlasUploadReady,
        boolean formalTextureAtlasReady,
        boolean formalModelBridgeReady,
        boolean atlasSkeletonStale,
        boolean lastReloadInvalidatedAtlasSkeleton,
        String layoutVersion,
        boolean lastAuditOk,
        String lastAuditError,
        double lastAuditDurationMs,
        int invalidLayout,
        int invalidModelCoordinate,
        int invalidFaceTileCoordinate,
        int sampleModelId,
        String sourceBlockState,
        String sourceSprite,
        String minecraftSpriteAtlas,
        int voxyAtlasBaseX,
        int voxyAtlasBaseY,
        String face0Tile,
        String face1Tile,
        String face2Tile,
        String face3Tile,
        String face4Tile,
        String face5Tile
) {
    static ForgeModelAtlasStats empty(long clearRuns) {
        return new ForgeModelAtlasStats(
                ForgeModelAtlasSkeleton.STAGE,
                0L,
                clearRuns,
                0L,
                0L,
                "none",
                0.0D,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                ForgeModelAtlasLayout.MODEL_TEXTURE_SIZE,
                ForgeModelAtlasLayout.MODEL_GRID_WIDTH,
                ForgeModelAtlasLayout.MODEL_GRID_HEIGHT,
                ForgeModelAtlasLayout.ATLAS_WIDTH,
                ForgeModelAtlasLayout.ATLAS_HEIGHT,
                ForgeModelAtlasLayout.FACES_PER_MODEL_X,
                ForgeModelAtlasLayout.FACES_PER_MODEL_Y,
                ForgeModelAtlasLayout.FACE_TILE_ORDER_KNOWN,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                ForgeModelAtlasLayout.LAYOUT_VERSION,
                false,
                "none",
                0.0D,
                0,
                0,
                0,
                -1,
                "none",
                "none",
                "none",
                -1,
                -1,
                "none",
                "none",
                "none",
                "none",
                "none",
                "none"
        );
    }
}
