package me.cortex.voxy.forge;

record ForgeFormalRendererReadiness(
        boolean geometryHeapReady,
        boolean metadataReady,
        boolean sectionGeometryManagerReady,
        boolean mdicCommandReady,
        boolean mdicDrawCountReady,
        boolean modelBridgeReady,
        boolean formalShaderInputBridgeReady,
        boolean atlasReady,
        boolean resourceReloadReady,
        boolean worldEngineReady,
        boolean dimensionReady,
        boolean infrastructureReady,
        boolean debugProofReady,
        boolean sampleBridgeReady,
        boolean oneBlockBakePrototypeReady,
        boolean oneBlockFormalUploadReady,
        boolean oneBlockFormalUploadAuditReady,
        boolean multiBlockBakePrototypeReady,
        boolean multiBlockFormalUploadReady,
        boolean multiBlockFormalUploadAuditReady,
        boolean formalModelBakeryLifecycleSkeletonReady,
        boolean reloadRebuildPrototypeReady,
        boolean aliasSafeDedupeReady,
        boolean formalModelFactorySkeletonReady,
        boolean formalModelFactoryLifecycleReady,
        boolean formalModelStoreSkeletonReady,
        boolean formalModelStoreOwnerReady,
        boolean formalPrerequisitesReady
) {
}
