package me.cortex.voxy.forge;

record ForgeOriginalVoxyMdicCommandGenerationStats(
        String stage,
        boolean originalMdicCommandGenerationOwnerReady,
        boolean originalMdicViewportCmdgenInputParityReady,
        boolean originalCmdgenCompOutputParityReady,
        boolean originalCmdgenReadbackAuditReady,
        boolean originalCmdgenBarrierAuditReady,
        boolean productionCmdgenCompUsed,
        boolean productionPrepCompUsed,
        boolean productionCullRasterUsed,
        boolean mdicSectionRendererCalled,
        boolean voxyRenderSystemCalled,
        boolean terrainDrawCalled,
        boolean glMultiDrawElementsIndirectCountCalled,
        boolean prepProgramReady,
        boolean cullProgramReady,
        boolean cmdgenProgramReady,
        boolean uniformBufferReady,
        boolean distanceCountBufferReady,
        boolean sharedIndexBufferReady,
        boolean vertexArrayReady,
        boolean viewportBuffersReady,
        boolean geometryMetadataBufferReady,
        boolean geometryBufferReady,
        boolean renderListInputReady,
        boolean visibilityBufferReady,
        boolean positionScratchBufferReady,
        long prepDispatchCount,
        long cullRasterCount,
        long cmdgenDispatchCount,
        long readbackAuditRuns,
        long readbackAuditFailures,
        int renderListSectionCount,
        int cmdGenDispatchX,
        int cmdGenDispatchY,
        int cmdGenDispatchZ,
        int opaqueDrawCount,
        int translucentDrawCount,
        int temporalOpaqueDrawCount,
        int cullCommandCount,
        int cullCommandInstanceCount,
        int cullCommandFirstIndex,
        int firstCommandCount,
        int firstCommandInstanceCount,
        int firstCommandFirstIndex,
        int firstCommandBaseVertex,
        int firstCommandBaseInstance,
        int firstPositionScratchWord0,
        int firstPositionScratchWord1,
        boolean drawCommandStride20Bytes,
        boolean drawCountLayoutMatchesOriginal,
        boolean cullCommandLayoutMatchesOriginal,
        boolean positionScratchReadbackOk,
        boolean noDebugCommandBuffersUsed,
        boolean formalRendererReady,
        boolean actualRendererDrawEnabled,
        boolean formalDrawPipelineReady,
        int lastGlError,
        String lifecycleState,
        String lastLifecycleEvent,
        String lastFailureReason
) {
    static ForgeOriginalVoxyMdicCommandGenerationStats unavailable(String reason) {
        return new ForgeOriginalVoxyMdicCommandGenerationStats(
                "V_ORIGINAL_MDIC_COMMAND_GENERATION_CHAIN",
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0L,
                0L,
                0L,
                0L,
                0L,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                0,
                "unavailable",
                "unavailable",
                reason == null || reason.isBlank() ? "original-mdic-command-generation-unavailable" : reason
        );
    }
}
