package me.cortex.voxy.forge;

record ForgeOriginalVoxyModelFactoryStats(
        boolean factoryReady,
        boolean originalModelFactoryUsed,
        boolean originalSoftwareModelTextureBakeryUsed,
        boolean originalModelStoreUsed,
        boolean asyncProcessorThreadReady,
        boolean renderThreadUploadPathUsed,
        boolean idMappingsReady,
        boolean metadataCacheReady,
        boolean fluidStateLutReady,
        boolean modelTextureDedupeReady,
        boolean uploadResultQueueReady,
        boolean mipChainAtlasUploadReady,
        boolean textureUtilsOriginalHelpersPorted,
        boolean textureUtilsByteForByteAuditReady,
        boolean biomeColourLutUploadReady,
        boolean uploadStreamPersistentMappedReady,
        boolean renderGenerationModelMissRequestRequeueReady,
        boolean originalModelStoreReadbackAuditReady,
        boolean modelDataReadbackOk,
        boolean modelColourReadbackOk,
        boolean atlasMipChainReadbackOk,
        int modelStoreReadbackAuditRuns,
        int modelStoreReadbackAuditFailures,
        int lastAuditedModelId,
        boolean customBlockStateIdMappingReady,
        boolean customBlockStateIdMappingPresent,
        String customBlockStateIdMappingSource,
        String lastModelStoreReadbackAuditFailureReason,
        int requestedBlockStateCount,
        int queuedBiomeCount,
        int queuedUploadResultCount,
        int biomeUploadResultCount,
        int queuedBlockBakeCount,
        int inFlightBlockBakeCount,
        int completedModelCount,
        int uploadedModelRecordCount,
        int uploadedModelColourCount,
        int uploadedAtlasFaceCount,
        int dedupeHitCount,
        int dedupeMissCount,
        int failedBakeCount,
        int modelTexture2idSize,
        int nextModelId,
        int lastRequestedBlockStateId,
        int lastUploadedBlockStateId,
        int lastUploadedModelId,
        int lastDuplicateBlockStateId,
        int lastDuplicateModelId,
        String lastFailureReason
) {
    static ForgeOriginalVoxyModelFactoryStats unavailable(String reason) {
        return new ForgeOriginalVoxyModelFactoryStats(
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                0,
                false,
                false,
                "none",
                "not-audited",
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                reason == null || reason.isBlank() ? "factory-unavailable" : reason
        );
    }
}
