package me.cortex.voxy.forge;

public record ForgeVoxyBuiltSectionStats(
        String dimension,
        int chunkX,
        int chunkZ,
        int sourceCpuEntries,
        int sectionsBuilt,
        int cacheEntriesWritten,
        int emptySections,
        long totalQuads,
        long geometryBytes,
        long occupancyBytes,
        String offsetsSemantic,
        String geometryFormat,
        String knownBitsMask,
        String knownFields,
        int uniqueModelIds,
        long missingModelId,
        long modelIdOverflow,
        int uniqueBiomeIds,
        long missingBiomeId,
        long biomeIdOverflow,
        long missingTexture,
        long missingGreedy,
        long naiveQuads,
        long mergedQuads,
        long quadsAfterMerge,
        double averageQuadArea,
        double mergeRatio,
        int maxQuadLength,
        int maxQuadWidth,
        long skippedTranslucent,
        long skippedNonMergeable,
        String sampleMergedRecordHex,
        String sampleMergedDecodedRecord,
        String offsetsSummary,
        String offsetsNamed,
        String samplePosition,
        String aabbSample,
        String sampleRecordHex,
        String sampleDecodedRecord,
        boolean occupancyPresent,
        boolean finalRendererFormat,
        double elapsedMs
) {
    public ForgeVoxyBuiltSectionStats withCacheEntriesWritten(int cacheEntriesWritten) {
        return new ForgeVoxyBuiltSectionStats(
                this.dimension,
                this.chunkX,
                this.chunkZ,
                this.sourceCpuEntries,
                this.sectionsBuilt,
                cacheEntriesWritten,
                this.emptySections,
                this.totalQuads,
                this.geometryBytes,
                this.occupancyBytes,
                this.offsetsSemantic,
                this.geometryFormat,
                this.knownBitsMask,
                this.knownFields,
                this.uniqueModelIds,
                this.missingModelId,
                this.modelIdOverflow,
                this.uniqueBiomeIds,
                this.missingBiomeId,
                this.biomeIdOverflow,
                this.missingTexture,
                this.missingGreedy,
                this.naiveQuads,
                this.mergedQuads,
                this.quadsAfterMerge,
                this.averageQuadArea,
                this.mergeRatio,
                this.maxQuadLength,
                this.maxQuadWidth,
                this.skippedTranslucent,
                this.skippedNonMergeable,
                this.sampleMergedRecordHex,
                this.sampleMergedDecodedRecord,
                this.offsetsSummary,
                this.offsetsNamed,
                this.samplePosition,
                this.aabbSample,
                this.sampleRecordHex,
                this.sampleDecodedRecord,
                this.occupancyPresent,
                this.finalRendererFormat,
                this.elapsedMs
        );
    }

    public ForgeVoxyBuiltSectionStats withElapsedMs(double elapsedMs) {
        return new ForgeVoxyBuiltSectionStats(
                this.dimension,
                this.chunkX,
                this.chunkZ,
                this.sourceCpuEntries,
                this.sectionsBuilt,
                this.cacheEntriesWritten,
                this.emptySections,
                this.totalQuads,
                this.geometryBytes,
                this.occupancyBytes,
                this.offsetsSemantic,
                this.geometryFormat,
                this.knownBitsMask,
                this.knownFields,
                this.uniqueModelIds,
                this.missingModelId,
                this.modelIdOverflow,
                this.uniqueBiomeIds,
                this.missingBiomeId,
                this.biomeIdOverflow,
                this.missingTexture,
                this.missingGreedy,
                this.naiveQuads,
                this.mergedQuads,
                this.quadsAfterMerge,
                this.averageQuadArea,
                this.mergeRatio,
                this.maxQuadLength,
                this.maxQuadWidth,
                this.skippedTranslucent,
                this.skippedNonMergeable,
                this.sampleMergedRecordHex,
                this.sampleMergedDecodedRecord,
                this.offsetsSummary,
                this.offsetsNamed,
                this.samplePosition,
                this.aabbSample,
                this.sampleRecordHex,
                this.sampleDecodedRecord,
                this.occupancyPresent,
                this.finalRendererFormat,
                elapsedMs
        );
    }
}
