package me.cortex.voxy.forge;

record ForgeModelBridgeResourceReloadStats(
        boolean reloadLifecycleSkeletonReady,
        boolean realResourceReloadListenerReady,
        boolean resourceReloadReady,
        long reloadEventsSeen,
        long realReloadEventsSeen,
        long simulatedReloadEventsSeen,
        String lastReloadStartedAt,
        String lastReloadFinishedAt,
        String lastReloadSource,
        String lastReloadThread,
        boolean reloadCleanupScheduled,
        boolean reloadCleanupOnRenderThread,
        boolean reloadCleanupCompleted,
        long reloadCleanupFailures,
        boolean modelBridgeInvalidatedOnReload,
        boolean placeholderBuffersInvalidatedOnReload,
        boolean placeholderBuffersStale,
        boolean realModelStoreStale,
        boolean textureAtlasStale,
        boolean formalShaderInputsStale,
        boolean bakedModelSamplesStale,
        boolean spriteSamplesStale,
        boolean lastReloadInvalidatedBakedModelSamples,
        boolean realModelRecordSampleStale,
        boolean lastReloadInvalidatedRealModelRecordSample,
        boolean sampleSetStale,
        boolean atlasSkeletonStale,
        boolean lastReloadInvalidatedAtlasSkeleton,
        boolean atlasPixelsStale,
        boolean lastReloadInvalidatedAtlasPixels,
        boolean formalShaderInputBridgeStale,
        boolean texturedDebugQuadStale,
        boolean texturedReadbackStale,
        boolean texturedMdicDebugStale,
        String lastReloadReason
) {
    static ForgeModelBridgeResourceReloadStats empty() {
        return new ForgeModelBridgeResourceReloadStats(
                true,
                false,
                false,
                0L,
                0L,
                0L,
                "none",
                "none",
                "NONE",
                "none",
                false,
                false,
                false,
                0L,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                "none"
        );
    }
}
