package me.cortex.voxy.forge;

record ForgeModelAtlasUploadStats(
        String stage,
        long uploadRuns,
        long uploadFailures,
        long auditRuns,
        long auditFailures,
        long clearRuns,
        String lastUploadError,
        double lastUploadDurationMs,
        boolean atlasTextureObjectCreated,
        int atlasTextureObjectId,
        boolean fullAtlasTextureCreated,
        boolean debugSmallAtlasFallback,
        int atlasWidth,
        int atlasHeight,
        int actualTextureWidth,
        int actualTextureHeight,
        String atlasFormat,
        boolean atlasPixelsUploaded,
        int uploadedFaces,
        int uploadedPixels,
        int missingFaces,
        boolean sampleAtlasPixelsUploaded,
        boolean realAtlasPixelUploadReady,
        boolean formalTextureAtlasReady,
        boolean formalTexturedShaderReady,
        boolean formalModelBridgeReady,
        boolean atlasPixelsStale,
        boolean lastReloadInvalidatedAtlasPixels,
        boolean lastUploadOk,
        boolean lastAuditOk,
        String lastAuditError,
        double lastAuditDurationMs,
        int lastUploadedFaces,
        int lastUploadedPixels,
        int lastMissingFaces,
        int lastPixelMismatches,
        boolean lastAtlasReadbackOk,
        int sampleModelId,
        int sourceBlockStateId,
        String sourceBlockState,
        String sourceSprite,
        String sourceSpriteAtlas,
        String face0Tile,
        String face1Tile,
        String face2Tile,
        String face3Tile,
        String face4Tile,
        String face5Tile,
        String face0Checksum,
        String face1Checksum,
        String face2Checksum,
        String face3Checksum,
        String face4Checksum,
        String face5Checksum
) {
    static ForgeModelAtlasUploadStats empty(long clearRuns) {
        return new ForgeModelAtlasUploadStats(
                ForgeModelAtlasPixelUploader.STAGE,
                0L,
                0L,
                0L,
                0L,
                clearRuns,
                "none",
                0.0D,
                false,
                0,
                false,
                false,
                ForgeModelAtlasLayout.ATLAS_WIDTH,
                ForgeModelAtlasLayout.ATLAS_HEIGHT,
                0,
                0,
                ForgeModelAtlasPixelUploader.ATLAS_FORMAT,
                false,
                0,
                0,
                0,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                "none",
                0.0D,
                0,
                0,
                0,
                0,
                false,
                -1,
                -1,
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none"
        );
    }
}
