package me.cortex.voxy.forge;

record ForgeBakedModelBridgeStats(
        String stage,
        long checkRuns,
        long clearRuns,
        long auditRuns,
        long auditFailures,
        String lastCheckError,
        double lastCheckDurationMs,
        boolean lastAuditOk,
        String lastAuditError,
        double lastAuditDurationMs,
        boolean placeholderModelIdsPresent,
        boolean canMapModelIdToBlockState,
        boolean bakedModelBridgeReady,
        boolean bakedModelSamplesReady,
        int sampledModelIds,
        int sampledBlockStates,
        int sampledBakedModels,
        int sampledQuads,
        int sampledSprites,
        int missingBakedModels,
        int missingSprites,
        int fluidLikeSamples,
        int emptyModelSamples,
        int unsupportedSamples,
        boolean renderLayerReadable,
        boolean spriteAtlasReadable,
        boolean spriteUvReadable,
        boolean minecraftBlockAtlasAccessible,
        String blockAtlasLocation,
        boolean customAtlasOwnershipReady,
        boolean customAtlasUploadReady,
        boolean formalTextureAtlasReady,
        boolean formalModelBridgeReady,
        boolean bakedModelSamplesStale,
        boolean spriteSamplesStale,
        boolean lastReloadInvalidatedBakedModelSamples,
        String currentDimension,
        int sampleModelId,
        int sampleBlockStateId,
        String sampleBlockState,
        boolean sampleFluidLike,
        String sampleBakedModelClass,
        String sampleRenderLayer,
        int sampleQuadCount,
        String sampleQuadDirection,
        int sampleQuadTintIndex,
        boolean sampleQuadHasTint,
        String sampleQuadSpriteName,
        String sampleQuadSpriteAtlas,
        String sampleQuadUvMin,
        String sampleQuadUvMax,
        String sampleQuadCullDirection,
        int sampleQuadVerticesLength,
        boolean sampleHasRealModelMetadata,
        boolean sampleHasAtlasSprite,
        boolean sampleHasAtlasUpload
) {
    static ForgeBakedModelBridgeStats empty(long clearRuns) {
        return new ForgeBakedModelBridgeStats(
                ForgeBakedModelBridge.STAGE,
                0L,
                clearRuns,
                0L,
                0L,
                "none",
                0.0D,
                false,
                "none",
                0.0D,
                false,
                false,
                false,
                false,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                false,
                false,
                true,
                "minecraft:textures/atlas/blocks.png",
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                "none",
                -1,
                -1,
                "none",
                false,
                "none",
                "unknown",
                0,
                "none",
                -1,
                false,
                "none",
                "none",
                "none",
                "none",
                "none",
                0,
                false,
                false,
                false
        );
    }
}
