package me.cortex.voxy.forge;

record ForgeRealModelStoreSampleStats(
        String stage,
        long buildRuns,
        long clearRuns,
        long auditRuns,
        long auditFailures,
        String lastBuildError,
        double lastBuildDurationMs,
        boolean realModelRecordSampleReady,
        boolean realModelRecordSampleBufferReady,
        int realModelRecordSampleCount,
        int realModelRecordBytes,
        String realModelRecordLayoutVersion,
        boolean formalLayoutCompatible,
        int sourceModelId,
        int sourceBlockStateId,
        String sourceBlockState,
        String sourceRenderLayer,
        String sourceSprite,
        String sourceSpriteAtlas,
        int sourceQuadCount,
        boolean realFaceDataSampleReady,
        String faceDataEncoded,
        boolean faceDataFormalCompatible,
        boolean realSpriteUvSampleReady,
        boolean modelColourSampleReady,
        int modelColourTintedFaces,
        int modelColourUntintedFaces,
        boolean biomeTintReady,
        boolean realTextureAtlasUploadReady,
        boolean formalTexturedShaderReady,
        boolean formalModelBridgeReady,
        boolean realModelRecordSampleStale,
        boolean lastReloadInvalidatedRealModelRecordSample,
        long generation,
        String dimension,
        boolean bufferStale,
        boolean lastAuditOk,
        String lastAuditError,
        double lastAuditDurationMs,
        int lastAuditedRecords,
        long lastAuditedBytes,
        int lastInvalidRecords,
        boolean lastModelDataBufferMatch,
        boolean lastModelColourBufferMatch,
        int faceCount,
        String sampleFaceDirection,
        String sampleFaceUvMin,
        String sampleFaceUvMax,
        int sampleFaceTintIndex,
        boolean sampleFaceHasTint,
        String sampleFaceCullDirection,
        int sampleFaceVerticesLength,
        int sampleFaceDataWord
) {
    static ForgeRealModelStoreSampleStats empty(long clearRuns) {
        return new ForgeRealModelStoreSampleStats(
                ForgeRealModelStoreSample.STAGE,
                0L,
                clearRuns,
                0L,
                0L,
                "none",
                0.0D,
                false,
                false,
                0,
                ForgeRealModelStoreSampleRecord.BYTES,
                ForgeRealModelStoreSampleRecord.LAYOUT_VERSION,
                ForgeRealModelStoreSampleRecord.FORMAL_LAYOUT_COMPATIBLE,
                -1,
                -1,
                "none",
                "unknown",
                "none",
                "none",
                0,
                false,
                "none",
                false,
                false,
                false,
                0,
                0,
                false,
                false,
                false,
                false,
                false,
                false,
                -1L,
                "none",
                false,
                false,
                "none",
                0.0D,
                0,
                0L,
                0,
                false,
                false,
                0,
                "none",
                "none",
                "none",
                -1,
                false,
                "none",
                0,
                -1
        );
    }
}
