package me.cortex.voxy.forge;

record ForgeModelBridgeReadinessStats(
        String stage,
        long checkRuns,
        long clearRuns,
        String lastCheckError,
        double lastCheckDurationMs,
        boolean placeholderModelIdsPresent,
        boolean stablePlaceholderModelIds,
        boolean canMapModelIdToBlockState,
        boolean placeholderModelStoreReady,
        boolean placeholderModelDataBufferReady,
        boolean placeholderModelColourBufferReady,
        boolean realModelStoreReady,
        boolean realModelFactoryReady,
        boolean modelBakeryBridgeReady,
        boolean textureAtlasReady,
        boolean realModelDataBufferReady,
        boolean realModelColourBufferReady,
        boolean biomeTintReady,
        boolean lightmapReady,
        boolean resourceReloadReady,
        boolean formalShaderInputsReady,
        boolean formalModelBridgeReady,
        int placeholderModelIdCount,
        int builtSectionUniqueModelIds,
        long missingModelRecords,
        String currentDimension,
        boolean activeWorldEnginePresent,
        String blockStateIdSource,
        int sampleModelId,
        int sampleBlockStateId,
        String sampleBlockState,
        boolean sampleIsPlaceholder,
        boolean sampleHasRealModelMetadata,
        boolean sampleHasTextureMetadata,
        String sampleNote
) {
    static ForgeModelBridgeReadinessStats empty(long clearRuns) {
        return new ForgeModelBridgeReadinessStats(
                ForgeModelBridgeReadiness.STAGE,
                0L,
                clearRuns,
                "none",
                0.0D,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                0L,
                "none",
                false,
                "none",
                -1,
                -1,
                "none",
                true,
                false,
                false,
                "not-checked"
        );
    }
}
