package me.cortex.voxy.forge;

record ForgeFormalCmdgenRealSectionDryRunAuditResult(
        boolean success,
        String error,
        double durationMs,
        boolean k1OwnerExists,
        boolean k2ViewportOwnerExists,
        boolean k3CommandGenerationOwnerExists,
        boolean k4VisibilityOwnerExists,
        boolean k5ValidationProgramExists,
        boolean originalCmdgenInspected,
        boolean sectionMetadataContractInspected,
        boolean realSectionDataUsed,
        boolean syntheticFixtureUsed,
        boolean validationBuffersIsolated,
        boolean debugMdicCommandBuffersUsedAsFormal,
        boolean cmdgenDryRunDispatchRun,
        boolean liveCommandGenerationRun,
        boolean drawCommandReadbackOk,
        boolean drawCountReadbackOk,
        boolean positionScratchReadbackOk,
        boolean firstCommandMatchesAcceptedSection,
        boolean firstCommandUsesRealSectionMetadata,
        int acceptedSectionCount,
        int generatedCommandCount,
        int generatedDrawCount,
        boolean multiDrawIndirectCountCalled,
        boolean mdicSectionRendererCalled,
        boolean voxyRenderSystemCalled,
        boolean formalDrawPipelineReady,
        boolean formalRendererReady,
        boolean actualRendererDrawEnabled
) {
    static ForgeFormalCmdgenRealSectionDryRunAuditResult failure(String error, double durationMs) {
        return new ForgeFormalCmdgenRealSectionDryRunAuditResult(
                false,
                error == null || error.isBlank() ? "unspecified" : error.replace(' ', '-'),
                durationMs,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0,
                0,
                0,
                false,
                false,
                false,
                false,
                false,
                false
        );
    }
}
